# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 14:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_email_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='/videos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.EmailAddress')),
            ],
        ),
    ]
