# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_booking_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='state',
        ),
        migrations.AddField(
            model_name='booking',
            name='oil_change',
            field=models.BooleanField(default=True),
        ),
    ]
