# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20160801_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='oil_change',
            field=models.BooleanField(choices=[(0, 'With Oil Change'), (1, 'With Out Oil Chnage')]),
        ),
    ]
