# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_auto_20160801_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='oil_change',
            field=models.CharField(choices=[(0, 'With Out Oil Chnage'), (1, 'With Oil Change')], default=1, max_length=55),
        ),
    ]
