# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20160801_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.IntegerField(choices=[(0, 'General Service'), (1, 'Minor Service'), (2, 'Major Service')], default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='oil_change',
            field=models.IntegerField(choices=[(0, 'With Out Oil Change'), (1, 'With Oil Change')], default=1),
        ),
    ]
