# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-01 19:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20160802_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='schedule_date',
            field=models.DateField(default=datetime.datetime(2016, 8, 1, 19, 39, 42, 25865, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
