# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_auto_20160803_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service_time',
            field=models.IntegerField(blank=True, choices=[(0, '9-10A.M'), (1, '10-11A.M'), (2, '11-12A.M'), (3, '12-1P.M'), (4, '1-2P.M'), (5, '2-3P.M'), (6, '3-4P.M'), (7, '4-5P.M'), (8, '5-6P.M')]),
        ),
    ]
