# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 09:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20160803_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode can have 6 digits', regex='^.{6}$')]),
        ),
    ]
