# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 06:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20160803_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='booking',
            name='brand',
            field=models.CharField(blank=True, max_length=30, verbose_name='Brand'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode should have 6 digits', regex='^[0-9]{6}$')]),
        ),
    ]
