# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=30, verbose_name='Status'),
        ),
    ]
