# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_auto_20160804_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='problem',
            field=models.CharField(blank=True, max_length=300, verbose_name='Describe the problem'),
        ),
    ]
