# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_assignmechanic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmechanic',
            old_name='mechanic',
            new_name='booking',
        ),
        migrations.AlterField(
            model_name='assignmechanic',
            name='mechanic_name',
            field=models.CharField(choices=[('RAMESH', 'Ramesh'), ('AKSHAY', 'Akshay')], default='RAMESH', max_length=30, verbose_name='Mechanic'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
