# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_auto_20160805_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmechanic',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking',
            name='assigned',
            field=models.ManyToManyField(to='services.AssignMechanic'),
        ),
        migrations.AlterField(
            model_name='assignmechanic',
            name='mechanic_name',
            field=models.CharField(blank=True, choices=[('RAMESH', 'Ramesh'), ('AKSHAY', 'Akshay')], max_length=30, verbose_name='Mechanic'),
        ),
    ]
