# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-05 12:48
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20160805_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmechanic',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='assignmechanic',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
    ]
